package com.app.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ApisExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public ApisExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andUpstreamUrlIsNull() {
            addCriterion("upstream_url is null");
            return (Criteria) this;
        }

        public Criteria andUpstreamUrlIsNotNull() {
            addCriterion("upstream_url is not null");
            return (Criteria) this;
        }

        public Criteria andUpstreamUrlEqualTo(String value) {
            addCriterion("upstream_url =", value, "upstreamUrl");
            return (Criteria) this;
        }

        public Criteria andUpstreamUrlNotEqualTo(String value) {
            addCriterion("upstream_url <>", value, "upstreamUrl");
            return (Criteria) this;
        }

        public Criteria andUpstreamUrlGreaterThan(String value) {
            addCriterion("upstream_url >", value, "upstreamUrl");
            return (Criteria) this;
        }

        public Criteria andUpstreamUrlGreaterThanOrEqualTo(String value) {
            addCriterion("upstream_url >=", value, "upstreamUrl");
            return (Criteria) this;
        }

        public Criteria andUpstreamUrlLessThan(String value) {
            addCriterion("upstream_url <", value, "upstreamUrl");
            return (Criteria) this;
        }

        public Criteria andUpstreamUrlLessThanOrEqualTo(String value) {
            addCriterion("upstream_url <=", value, "upstreamUrl");
            return (Criteria) this;
        }

        public Criteria andUpstreamUrlLike(String value) {
            addCriterion("upstream_url like", value, "upstreamUrl");
            return (Criteria) this;
        }

        public Criteria andUpstreamUrlNotLike(String value) {
            addCriterion("upstream_url not like", value, "upstreamUrl");
            return (Criteria) this;
        }

        public Criteria andUpstreamUrlIn(List<String> values) {
            addCriterion("upstream_url in", values, "upstreamUrl");
            return (Criteria) this;
        }

        public Criteria andUpstreamUrlNotIn(List<String> values) {
            addCriterion("upstream_url not in", values, "upstreamUrl");
            return (Criteria) this;
        }

        public Criteria andUpstreamUrlBetween(String value1, String value2) {
            addCriterion("upstream_url between", value1, value2, "upstreamUrl");
            return (Criteria) this;
        }

        public Criteria andUpstreamUrlNotBetween(String value1, String value2) {
            addCriterion("upstream_url not between", value1, value2, "upstreamUrl");
            return (Criteria) this;
        }

        public Criteria andPreserveHostIsNull() {
            addCriterion("preserve_host is null");
            return (Criteria) this;
        }

        public Criteria andPreserveHostIsNotNull() {
            addCriterion("preserve_host is not null");
            return (Criteria) this;
        }

        public Criteria andPreserveHostEqualTo(Boolean value) {
            addCriterion("preserve_host =", value, "preserveHost");
            return (Criteria) this;
        }

        public Criteria andPreserveHostNotEqualTo(Boolean value) {
            addCriterion("preserve_host <>", value, "preserveHost");
            return (Criteria) this;
        }

        public Criteria andPreserveHostGreaterThan(Boolean value) {
            addCriterion("preserve_host >", value, "preserveHost");
            return (Criteria) this;
        }

        public Criteria andPreserveHostGreaterThanOrEqualTo(Boolean value) {
            addCriterion("preserve_host >=", value, "preserveHost");
            return (Criteria) this;
        }

        public Criteria andPreserveHostLessThan(Boolean value) {
            addCriterion("preserve_host <", value, "preserveHost");
            return (Criteria) this;
        }

        public Criteria andPreserveHostLessThanOrEqualTo(Boolean value) {
            addCriterion("preserve_host <=", value, "preserveHost");
            return (Criteria) this;
        }

        public Criteria andPreserveHostIn(List<Boolean> values) {
            addCriterion("preserve_host in", values, "preserveHost");
            return (Criteria) this;
        }

        public Criteria andPreserveHostNotIn(List<Boolean> values) {
            addCriterion("preserve_host not in", values, "preserveHost");
            return (Criteria) this;
        }

        public Criteria andPreserveHostBetween(Boolean value1, Boolean value2) {
            addCriterion("preserve_host between", value1, value2, "preserveHost");
            return (Criteria) this;
        }

        public Criteria andPreserveHostNotBetween(Boolean value1, Boolean value2) {
            addCriterion("preserve_host not between", value1, value2, "preserveHost");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andRetriesIsNull() {
            addCriterion("retries is null");
            return (Criteria) this;
        }

        public Criteria andRetriesIsNotNull() {
            addCriterion("retries is not null");
            return (Criteria) this;
        }

        public Criteria andRetriesEqualTo(Short value) {
            addCriterion("retries =", value, "retries");
            return (Criteria) this;
        }

        public Criteria andRetriesNotEqualTo(Short value) {
            addCriterion("retries <>", value, "retries");
            return (Criteria) this;
        }

        public Criteria andRetriesGreaterThan(Short value) {
            addCriterion("retries >", value, "retries");
            return (Criteria) this;
        }

        public Criteria andRetriesGreaterThanOrEqualTo(Short value) {
            addCriterion("retries >=", value, "retries");
            return (Criteria) this;
        }

        public Criteria andRetriesLessThan(Short value) {
            addCriterion("retries <", value, "retries");
            return (Criteria) this;
        }

        public Criteria andRetriesLessThanOrEqualTo(Short value) {
            addCriterion("retries <=", value, "retries");
            return (Criteria) this;
        }

        public Criteria andRetriesIn(List<Short> values) {
            addCriterion("retries in", values, "retries");
            return (Criteria) this;
        }

        public Criteria andRetriesNotIn(List<Short> values) {
            addCriterion("retries not in", values, "retries");
            return (Criteria) this;
        }

        public Criteria andRetriesBetween(Short value1, Short value2) {
            addCriterion("retries between", value1, value2, "retries");
            return (Criteria) this;
        }

        public Criteria andRetriesNotBetween(Short value1, Short value2) {
            addCriterion("retries not between", value1, value2, "retries");
            return (Criteria) this;
        }

        public Criteria andHttpsOnlyIsNull() {
            addCriterion("https_only is null");
            return (Criteria) this;
        }

        public Criteria andHttpsOnlyIsNotNull() {
            addCriterion("https_only is not null");
            return (Criteria) this;
        }

        public Criteria andHttpsOnlyEqualTo(Boolean value) {
            addCriterion("https_only =", value, "httpsOnly");
            return (Criteria) this;
        }

        public Criteria andHttpsOnlyNotEqualTo(Boolean value) {
            addCriterion("https_only <>", value, "httpsOnly");
            return (Criteria) this;
        }

        public Criteria andHttpsOnlyGreaterThan(Boolean value) {
            addCriterion("https_only >", value, "httpsOnly");
            return (Criteria) this;
        }

        public Criteria andHttpsOnlyGreaterThanOrEqualTo(Boolean value) {
            addCriterion("https_only >=", value, "httpsOnly");
            return (Criteria) this;
        }

        public Criteria andHttpsOnlyLessThan(Boolean value) {
            addCriterion("https_only <", value, "httpsOnly");
            return (Criteria) this;
        }

        public Criteria andHttpsOnlyLessThanOrEqualTo(Boolean value) {
            addCriterion("https_only <=", value, "httpsOnly");
            return (Criteria) this;
        }

        public Criteria andHttpsOnlyIn(List<Boolean> values) {
            addCriterion("https_only in", values, "httpsOnly");
            return (Criteria) this;
        }

        public Criteria andHttpsOnlyNotIn(List<Boolean> values) {
            addCriterion("https_only not in", values, "httpsOnly");
            return (Criteria) this;
        }

        public Criteria andHttpsOnlyBetween(Boolean value1, Boolean value2) {
            addCriterion("https_only between", value1, value2, "httpsOnly");
            return (Criteria) this;
        }

        public Criteria andHttpsOnlyNotBetween(Boolean value1, Boolean value2) {
            addCriterion("https_only not between", value1, value2, "httpsOnly");
            return (Criteria) this;
        }

        public Criteria andHttpIfTerminatedIsNull() {
            addCriterion("http_if_terminated is null");
            return (Criteria) this;
        }

        public Criteria andHttpIfTerminatedIsNotNull() {
            addCriterion("http_if_terminated is not null");
            return (Criteria) this;
        }

        public Criteria andHttpIfTerminatedEqualTo(Boolean value) {
            addCriterion("http_if_terminated =", value, "httpIfTerminated");
            return (Criteria) this;
        }

        public Criteria andHttpIfTerminatedNotEqualTo(Boolean value) {
            addCriterion("http_if_terminated <>", value, "httpIfTerminated");
            return (Criteria) this;
        }

        public Criteria andHttpIfTerminatedGreaterThan(Boolean value) {
            addCriterion("http_if_terminated >", value, "httpIfTerminated");
            return (Criteria) this;
        }

        public Criteria andHttpIfTerminatedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("http_if_terminated >=", value, "httpIfTerminated");
            return (Criteria) this;
        }

        public Criteria andHttpIfTerminatedLessThan(Boolean value) {
            addCriterion("http_if_terminated <", value, "httpIfTerminated");
            return (Criteria) this;
        }

        public Criteria andHttpIfTerminatedLessThanOrEqualTo(Boolean value) {
            addCriterion("http_if_terminated <=", value, "httpIfTerminated");
            return (Criteria) this;
        }

        public Criteria andHttpIfTerminatedIn(List<Boolean> values) {
            addCriterion("http_if_terminated in", values, "httpIfTerminated");
            return (Criteria) this;
        }

        public Criteria andHttpIfTerminatedNotIn(List<Boolean> values) {
            addCriterion("http_if_terminated not in", values, "httpIfTerminated");
            return (Criteria) this;
        }

        public Criteria andHttpIfTerminatedBetween(Boolean value1, Boolean value2) {
            addCriterion("http_if_terminated between", value1, value2, "httpIfTerminated");
            return (Criteria) this;
        }

        public Criteria andHttpIfTerminatedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("http_if_terminated not between", value1, value2, "httpIfTerminated");
            return (Criteria) this;
        }

        public Criteria andHostsIsNull() {
            addCriterion("hosts is null");
            return (Criteria) this;
        }

        public Criteria andHostsIsNotNull() {
            addCriterion("hosts is not null");
            return (Criteria) this;
        }

        public Criteria andHostsEqualTo(String value) {
            addCriterion("hosts =", value, "hosts");
            return (Criteria) this;
        }

        public Criteria andHostsNotEqualTo(String value) {
            addCriterion("hosts <>", value, "hosts");
            return (Criteria) this;
        }

        public Criteria andHostsGreaterThan(String value) {
            addCriterion("hosts >", value, "hosts");
            return (Criteria) this;
        }

        public Criteria andHostsGreaterThanOrEqualTo(String value) {
            addCriterion("hosts >=", value, "hosts");
            return (Criteria) this;
        }

        public Criteria andHostsLessThan(String value) {
            addCriterion("hosts <", value, "hosts");
            return (Criteria) this;
        }

        public Criteria andHostsLessThanOrEqualTo(String value) {
            addCriterion("hosts <=", value, "hosts");
            return (Criteria) this;
        }

        public Criteria andHostsLike(String value) {
            addCriterion("hosts like", value, "hosts");
            return (Criteria) this;
        }

        public Criteria andHostsNotLike(String value) {
            addCriterion("hosts not like", value, "hosts");
            return (Criteria) this;
        }

        public Criteria andHostsIn(List<String> values) {
            addCriterion("hosts in", values, "hosts");
            return (Criteria) this;
        }

        public Criteria andHostsNotIn(List<String> values) {
            addCriterion("hosts not in", values, "hosts");
            return (Criteria) this;
        }

        public Criteria andHostsBetween(String value1, String value2) {
            addCriterion("hosts between", value1, value2, "hosts");
            return (Criteria) this;
        }

        public Criteria andHostsNotBetween(String value1, String value2) {
            addCriterion("hosts not between", value1, value2, "hosts");
            return (Criteria) this;
        }

        public Criteria andUrisIsNull() {
            addCriterion("uris is null");
            return (Criteria) this;
        }

        public Criteria andUrisIsNotNull() {
            addCriterion("uris is not null");
            return (Criteria) this;
        }

        public Criteria andUrisEqualTo(String value) {
            addCriterion("uris =", value, "uris");
            return (Criteria) this;
        }

        public Criteria andUrisNotEqualTo(String value) {
            addCriterion("uris <>", value, "uris");
            return (Criteria) this;
        }

        public Criteria andUrisGreaterThan(String value) {
            addCriterion("uris >", value, "uris");
            return (Criteria) this;
        }

        public Criteria andUrisGreaterThanOrEqualTo(String value) {
            addCriterion("uris >=", value, "uris");
            return (Criteria) this;
        }

        public Criteria andUrisLessThan(String value) {
            addCriterion("uris <", value, "uris");
            return (Criteria) this;
        }

        public Criteria andUrisLessThanOrEqualTo(String value) {
            addCriterion("uris <=", value, "uris");
            return (Criteria) this;
        }

        public Criteria andUrisLike(String value) {
            addCriterion("uris like", value, "uris");
            return (Criteria) this;
        }

        public Criteria andUrisNotLike(String value) {
            addCriterion("uris not like", value, "uris");
            return (Criteria) this;
        }

        public Criteria andUrisIn(List<String> values) {
            addCriterion("uris in", values, "uris");
            return (Criteria) this;
        }

        public Criteria andUrisNotIn(List<String> values) {
            addCriterion("uris not in", values, "uris");
            return (Criteria) this;
        }

        public Criteria andUrisBetween(String value1, String value2) {
            addCriterion("uris between", value1, value2, "uris");
            return (Criteria) this;
        }

        public Criteria andUrisNotBetween(String value1, String value2) {
            addCriterion("uris not between", value1, value2, "uris");
            return (Criteria) this;
        }

        public Criteria andMethodsIsNull() {
            addCriterion("methods is null");
            return (Criteria) this;
        }

        public Criteria andMethodsIsNotNull() {
            addCriterion("methods is not null");
            return (Criteria) this;
        }

        public Criteria andMethodsEqualTo(String value) {
            addCriterion("methods =", value, "methods");
            return (Criteria) this;
        }

        public Criteria andMethodsNotEqualTo(String value) {
            addCriterion("methods <>", value, "methods");
            return (Criteria) this;
        }

        public Criteria andMethodsGreaterThan(String value) {
            addCriterion("methods >", value, "methods");
            return (Criteria) this;
        }

        public Criteria andMethodsGreaterThanOrEqualTo(String value) {
            addCriterion("methods >=", value, "methods");
            return (Criteria) this;
        }

        public Criteria andMethodsLessThan(String value) {
            addCriterion("methods <", value, "methods");
            return (Criteria) this;
        }

        public Criteria andMethodsLessThanOrEqualTo(String value) {
            addCriterion("methods <=", value, "methods");
            return (Criteria) this;
        }

        public Criteria andMethodsLike(String value) {
            addCriterion("methods like", value, "methods");
            return (Criteria) this;
        }

        public Criteria andMethodsNotLike(String value) {
            addCriterion("methods not like", value, "methods");
            return (Criteria) this;
        }

        public Criteria andMethodsIn(List<String> values) {
            addCriterion("methods in", values, "methods");
            return (Criteria) this;
        }

        public Criteria andMethodsNotIn(List<String> values) {
            addCriterion("methods not in", values, "methods");
            return (Criteria) this;
        }

        public Criteria andMethodsBetween(String value1, String value2) {
            addCriterion("methods between", value1, value2, "methods");
            return (Criteria) this;
        }

        public Criteria andMethodsNotBetween(String value1, String value2) {
            addCriterion("methods not between", value1, value2, "methods");
            return (Criteria) this;
        }

        public Criteria andStripUriIsNull() {
            addCriterion("strip_uri is null");
            return (Criteria) this;
        }

        public Criteria andStripUriIsNotNull() {
            addCriterion("strip_uri is not null");
            return (Criteria) this;
        }

        public Criteria andStripUriEqualTo(Boolean value) {
            addCriterion("strip_uri =", value, "stripUri");
            return (Criteria) this;
        }

        public Criteria andStripUriNotEqualTo(Boolean value) {
            addCriterion("strip_uri <>", value, "stripUri");
            return (Criteria) this;
        }

        public Criteria andStripUriGreaterThan(Boolean value) {
            addCriterion("strip_uri >", value, "stripUri");
            return (Criteria) this;
        }

        public Criteria andStripUriGreaterThanOrEqualTo(Boolean value) {
            addCriterion("strip_uri >=", value, "stripUri");
            return (Criteria) this;
        }

        public Criteria andStripUriLessThan(Boolean value) {
            addCriterion("strip_uri <", value, "stripUri");
            return (Criteria) this;
        }

        public Criteria andStripUriLessThanOrEqualTo(Boolean value) {
            addCriterion("strip_uri <=", value, "stripUri");
            return (Criteria) this;
        }

        public Criteria andStripUriIn(List<Boolean> values) {
            addCriterion("strip_uri in", values, "stripUri");
            return (Criteria) this;
        }

        public Criteria andStripUriNotIn(List<Boolean> values) {
            addCriterion("strip_uri not in", values, "stripUri");
            return (Criteria) this;
        }

        public Criteria andStripUriBetween(Boolean value1, Boolean value2) {
            addCriterion("strip_uri between", value1, value2, "stripUri");
            return (Criteria) this;
        }

        public Criteria andStripUriNotBetween(Boolean value1, Boolean value2) {
            addCriterion("strip_uri not between", value1, value2, "stripUri");
            return (Criteria) this;
        }

        public Criteria andUpstreamConnectTimeoutIsNull() {
            addCriterion("upstream_connect_timeout is null");
            return (Criteria) this;
        }

        public Criteria andUpstreamConnectTimeoutIsNotNull() {
            addCriterion("upstream_connect_timeout is not null");
            return (Criteria) this;
        }

        public Criteria andUpstreamConnectTimeoutEqualTo(Integer value) {
            addCriterion("upstream_connect_timeout =", value, "upstreamConnectTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamConnectTimeoutNotEqualTo(Integer value) {
            addCriterion("upstream_connect_timeout <>", value, "upstreamConnectTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamConnectTimeoutGreaterThan(Integer value) {
            addCriterion("upstream_connect_timeout >", value, "upstreamConnectTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamConnectTimeoutGreaterThanOrEqualTo(Integer value) {
            addCriterion("upstream_connect_timeout >=", value, "upstreamConnectTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamConnectTimeoutLessThan(Integer value) {
            addCriterion("upstream_connect_timeout <", value, "upstreamConnectTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamConnectTimeoutLessThanOrEqualTo(Integer value) {
            addCriterion("upstream_connect_timeout <=", value, "upstreamConnectTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamConnectTimeoutIn(List<Integer> values) {
            addCriterion("upstream_connect_timeout in", values, "upstreamConnectTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamConnectTimeoutNotIn(List<Integer> values) {
            addCriterion("upstream_connect_timeout not in", values, "upstreamConnectTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamConnectTimeoutBetween(Integer value1, Integer value2) {
            addCriterion("upstream_connect_timeout between", value1, value2, "upstreamConnectTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamConnectTimeoutNotBetween(Integer value1, Integer value2) {
            addCriterion("upstream_connect_timeout not between", value1, value2, "upstreamConnectTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamSendTimeoutIsNull() {
            addCriterion("upstream_send_timeout is null");
            return (Criteria) this;
        }

        public Criteria andUpstreamSendTimeoutIsNotNull() {
            addCriterion("upstream_send_timeout is not null");
            return (Criteria) this;
        }

        public Criteria andUpstreamSendTimeoutEqualTo(Integer value) {
            addCriterion("upstream_send_timeout =", value, "upstreamSendTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamSendTimeoutNotEqualTo(Integer value) {
            addCriterion("upstream_send_timeout <>", value, "upstreamSendTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamSendTimeoutGreaterThan(Integer value) {
            addCriterion("upstream_send_timeout >", value, "upstreamSendTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamSendTimeoutGreaterThanOrEqualTo(Integer value) {
            addCriterion("upstream_send_timeout >=", value, "upstreamSendTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamSendTimeoutLessThan(Integer value) {
            addCriterion("upstream_send_timeout <", value, "upstreamSendTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamSendTimeoutLessThanOrEqualTo(Integer value) {
            addCriterion("upstream_send_timeout <=", value, "upstreamSendTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamSendTimeoutIn(List<Integer> values) {
            addCriterion("upstream_send_timeout in", values, "upstreamSendTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamSendTimeoutNotIn(List<Integer> values) {
            addCriterion("upstream_send_timeout not in", values, "upstreamSendTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamSendTimeoutBetween(Integer value1, Integer value2) {
            addCriterion("upstream_send_timeout between", value1, value2, "upstreamSendTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamSendTimeoutNotBetween(Integer value1, Integer value2) {
            addCriterion("upstream_send_timeout not between", value1, value2, "upstreamSendTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamReadTimeoutIsNull() {
            addCriterion("upstream_read_timeout is null");
            return (Criteria) this;
        }

        public Criteria andUpstreamReadTimeoutIsNotNull() {
            addCriterion("upstream_read_timeout is not null");
            return (Criteria) this;
        }

        public Criteria andUpstreamReadTimeoutEqualTo(Integer value) {
            addCriterion("upstream_read_timeout =", value, "upstreamReadTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamReadTimeoutNotEqualTo(Integer value) {
            addCriterion("upstream_read_timeout <>", value, "upstreamReadTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamReadTimeoutGreaterThan(Integer value) {
            addCriterion("upstream_read_timeout >", value, "upstreamReadTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamReadTimeoutGreaterThanOrEqualTo(Integer value) {
            addCriterion("upstream_read_timeout >=", value, "upstreamReadTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamReadTimeoutLessThan(Integer value) {
            addCriterion("upstream_read_timeout <", value, "upstreamReadTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamReadTimeoutLessThanOrEqualTo(Integer value) {
            addCriterion("upstream_read_timeout <=", value, "upstreamReadTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamReadTimeoutIn(List<Integer> values) {
            addCriterion("upstream_read_timeout in", values, "upstreamReadTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamReadTimeoutNotIn(List<Integer> values) {
            addCriterion("upstream_read_timeout not in", values, "upstreamReadTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamReadTimeoutBetween(Integer value1, Integer value2) {
            addCriterion("upstream_read_timeout between", value1, value2, "upstreamReadTimeout");
            return (Criteria) this;
        }

        public Criteria andUpstreamReadTimeoutNotBetween(Integer value1, Integer value2) {
            addCriterion("upstream_read_timeout not between", value1, value2, "upstreamReadTimeout");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table apis
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 24 14:53:05 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}