package com.app.entity;

import java.util.Date;

public class Apis {

    @Override
    public String toString() {
        return "Apis{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", upstreamUrl='" + upstreamUrl + '\'' +
                ", preserveHost=" + preserveHost +
                ", createdAt=" + createdAt +
                ", retries=" + retries +
                ", httpsOnly=" + httpsOnly +
                ", httpIfTerminated=" + httpIfTerminated +
                ", hosts='" + hosts + '\'' +
                ", uris='" + uris + '\'' +
                ", methods='" + methods + '\'' +
                ", stripUri=" + stripUri +
                ", upstreamConnectTimeout=" + upstreamConnectTimeout +
                ", upstreamSendTimeout=" + upstreamSendTimeout +
                ", upstreamReadTimeout=" + upstreamReadTimeout +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apis.id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apis.name
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apis.upstream_url
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String upstreamUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apis.preserve_host
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Boolean preserveHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apis.created_at
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apis.retries
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Short retries;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apis.https_only
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Boolean httpsOnly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apis.http_if_terminated
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Boolean httpIfTerminated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apis.hosts
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String hosts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apis.uris
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String uris;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apis.methods
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String methods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apis.strip_uri
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Boolean stripUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apis.upstream_connect_timeout
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Integer upstreamConnectTimeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apis.upstream_send_timeout
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Integer upstreamSendTimeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apis.upstream_read_timeout
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Integer upstreamReadTimeout;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apis.id
     *
     * @return the value of apis.id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apis.id
     *
     * @param id the value for apis.id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apis.name
     *
     * @return the value of apis.name
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apis.name
     *
     * @param name the value for apis.name
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apis.upstream_url
     *
     * @return the value of apis.upstream_url
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getUpstreamUrl() {
        return upstreamUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apis.upstream_url
     *
     * @param upstreamUrl the value for apis.upstream_url
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setUpstreamUrl(String upstreamUrl) {
        this.upstreamUrl = upstreamUrl == null ? null : upstreamUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apis.preserve_host
     *
     * @return the value of apis.preserve_host
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Boolean getPreserveHost() {
        return preserveHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apis.preserve_host
     *
     * @param preserveHost the value for apis.preserve_host
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setPreserveHost(Boolean preserveHost) {
        this.preserveHost = preserveHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apis.created_at
     *
     * @return the value of apis.created_at
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apis.created_at
     *
     * @param createdAt the value for apis.created_at
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apis.retries
     *
     * @return the value of apis.retries
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Short getRetries() {
        return retries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apis.retries
     *
     * @param retries the value for apis.retries
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setRetries(Short retries) {
        this.retries = retries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apis.https_only
     *
     * @return the value of apis.https_only
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Boolean getHttpsOnly() {
        return httpsOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apis.https_only
     *
     * @param httpsOnly the value for apis.https_only
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setHttpsOnly(Boolean httpsOnly) {
        this.httpsOnly = httpsOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apis.http_if_terminated
     *
     * @return the value of apis.http_if_terminated
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Boolean getHttpIfTerminated() {
        return httpIfTerminated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apis.http_if_terminated
     *
     * @param httpIfTerminated the value for apis.http_if_terminated
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setHttpIfTerminated(Boolean httpIfTerminated) {
        this.httpIfTerminated = httpIfTerminated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apis.hosts
     *
     * @return the value of apis.hosts
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getHosts() {
        return hosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apis.hosts
     *
     * @param hosts the value for apis.hosts
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setHosts(String hosts) {
        this.hosts = hosts == null ? null : hosts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apis.uris
     *
     * @return the value of apis.uris
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getUris() {
        return uris;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apis.uris
     *
     * @param uris the value for apis.uris
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setUris(String uris) {
        this.uris = uris == null ? null : uris.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apis.methods
     *
     * @return the value of apis.methods
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getMethods() {
        return methods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apis.methods
     *
     * @param methods the value for apis.methods
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setMethods(String methods) {
        this.methods = methods == null ? null : methods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apis.strip_uri
     *
     * @return the value of apis.strip_uri
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Boolean getStripUri() {
        return stripUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apis.strip_uri
     *
     * @param stripUri the value for apis.strip_uri
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setStripUri(Boolean stripUri) {
        this.stripUri = stripUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apis.upstream_connect_timeout
     *
     * @return the value of apis.upstream_connect_timeout
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Integer getUpstreamConnectTimeout() {
        return upstreamConnectTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apis.upstream_connect_timeout
     *
     * @param upstreamConnectTimeout the value for apis.upstream_connect_timeout
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setUpstreamConnectTimeout(Integer upstreamConnectTimeout) {
        this.upstreamConnectTimeout = upstreamConnectTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apis.upstream_send_timeout
     *
     * @return the value of apis.upstream_send_timeout
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Integer getUpstreamSendTimeout() {
        return upstreamSendTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apis.upstream_send_timeout
     *
     * @param upstreamSendTimeout the value for apis.upstream_send_timeout
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setUpstreamSendTimeout(Integer upstreamSendTimeout) {
        this.upstreamSendTimeout = upstreamSendTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apis.upstream_read_timeout
     *
     * @return the value of apis.upstream_read_timeout
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Integer getUpstreamReadTimeout() {
        return upstreamReadTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apis.upstream_read_timeout
     *
     * @param upstreamReadTimeout the value for apis.upstream_read_timeout
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setUpstreamReadTimeout(Integer upstreamReadTimeout) {
        this.upstreamReadTimeout = upstreamReadTimeout;
    }
}