package com.app.entity;

import java.util.Date;

public class Consumers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumers.id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumers.custom_id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String customId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumers.username
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumers.created_at
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumers.id
     *
     * @return the value of consumers.id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumers.id
     *
     * @param id the value for consumers.id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumers.custom_id
     *
     * @return the value of consumers.custom_id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getCustomId() {
        return customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumers.custom_id
     *
     * @param customId the value for consumers.custom_id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setCustomId(String customId) {
        this.customId = customId == null ? null : customId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumers.username
     *
     * @return the value of consumers.username
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumers.username
     *
     * @param username the value for consumers.username
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumers.created_at
     *
     * @return the value of consumers.created_at
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumers.created_at
     *
     * @param createdAt the value for consumers.created_at
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}