package com.app.entity;

import java.util.Date;

public class KongUser {
    @Override
    public String toString() {
        return "KongUser{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", password='" + password + '\'' +
                ", roleType='" + roleType + '\'' +
                ", createdAt=" + createdAt +
                ", isUse='" + isUse + '\'' +
                ", lastLogin=" + lastLogin +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kong_user.id
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    private Object id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kong_user.name
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kong_user.password
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kong_user.role_type
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    private String roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kong_user.created_at
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kong_user.is_use
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    private String isUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kong_user.last_login
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    private Date lastLogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kong_user.id
     *
     * @return the value of kong_user.id
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kong_user.id
     *
     * @param id the value for kong_user.id
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kong_user.name
     *
     * @return the value of kong_user.name
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kong_user.name
     *
     * @param name the value for kong_user.name
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kong_user.password
     *
     * @return the value of kong_user.password
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kong_user.password
     *
     * @param password the value for kong_user.password
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kong_user.role_type
     *
     * @return the value of kong_user.role_type
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kong_user.role_type
     *
     * @param roleType the value for kong_user.role_type
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kong_user.created_at
     *
     * @return the value of kong_user.created_at
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kong_user.created_at
     *
     * @param createdAt the value for kong_user.created_at
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kong_user.is_use
     *
     * @return the value of kong_user.is_use
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    public String getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kong_user.is_use
     *
     * @param isUse the value for kong_user.is_use
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    public void setIsUse(String isUse) {
        this.isUse = isUse == null ? null : isUse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kong_user.last_login
     *
     * @return the value of kong_user.last_login
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kong_user.last_login
     *
     * @param lastLogin the value for kong_user.last_login
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
}