package com.app.entity;

import java.util.Date;

public class Plugins extends PluginsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.api_id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String apiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.consumer_id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String consumerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.config
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Object config;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.enabled
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.created_at
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.api_id
     *
     * @return the value of plugins.api_id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getApiId() {
        return apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.api_id
     *
     * @param apiId the value for plugins.api_id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setApiId(String apiId) {
        this.apiId = apiId == null ? null : apiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.consumer_id
     *
     * @return the value of plugins.consumer_id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getConsumerId() {
        return consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.consumer_id
     *
     * @param consumerId the value for plugins.consumer_id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setConsumerId(String consumerId) {
        this.consumerId = consumerId == null ? null : consumerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.config
     *
     * @return the value of plugins.config
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Object getConfig() {
        return config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.config
     *
     * @param config the value for plugins.config
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setConfig(Object config) {
        this.config = config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.enabled
     *
     * @return the value of plugins.enabled
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.enabled
     *
     * @param enabled the value for plugins.enabled
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.created_at
     *
     * @return the value of plugins.created_at
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.created_at
     *
     * @param createdAt the value for plugins.created_at
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}