package com.app.entity;

public class PluginsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugins.name
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.id
     *
     * @return the value of plugins.id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.id
     *
     * @param id the value for plugins.id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugins.name
     *
     * @return the value of plugins.name
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugins.name
     *
     * @param name the value for plugins.name
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}