package com.app.entity;

import java.util.Date;

public class Targets {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column targets.id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column targets.target
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column targets.weight
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column targets.upstream_id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String upstreamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column targets.created_at
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column targets.id
     *
     * @return the value of targets.id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column targets.id
     *
     * @param id the value for targets.id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column targets.target
     *
     * @return the value of targets.target
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column targets.target
     *
     * @param target the value for targets.target
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column targets.weight
     *
     * @return the value of targets.weight
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column targets.weight
     *
     * @param weight the value for targets.weight
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column targets.upstream_id
     *
     * @return the value of targets.upstream_id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getUpstreamId() {
        return upstreamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column targets.upstream_id
     *
     * @param upstreamId the value for targets.upstream_id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setUpstreamId(String upstreamId) {
        this.upstreamId = upstreamId == null ? null : upstreamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column targets.created_at
     *
     * @return the value of targets.created_at
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column targets.created_at
     *
     * @param createdAt the value for targets.created_at
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}