package com.app.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UpstreamsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table upstreams
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table upstreams
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table upstreams
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upstreams
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public UpstreamsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upstreams
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upstreams
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upstreams
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upstreams
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upstreams
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upstreams
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upstreams
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upstreams
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upstreams
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upstreams
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table upstreams
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSlotsIsNull() {
            addCriterion("slots is null");
            return (Criteria) this;
        }

        public Criteria andSlotsIsNotNull() {
            addCriterion("slots is not null");
            return (Criteria) this;
        }

        public Criteria andSlotsEqualTo(Integer value) {
            addCriterion("slots =", value, "slots");
            return (Criteria) this;
        }

        public Criteria andSlotsNotEqualTo(Integer value) {
            addCriterion("slots <>", value, "slots");
            return (Criteria) this;
        }

        public Criteria andSlotsGreaterThan(Integer value) {
            addCriterion("slots >", value, "slots");
            return (Criteria) this;
        }

        public Criteria andSlotsGreaterThanOrEqualTo(Integer value) {
            addCriterion("slots >=", value, "slots");
            return (Criteria) this;
        }

        public Criteria andSlotsLessThan(Integer value) {
            addCriterion("slots <", value, "slots");
            return (Criteria) this;
        }

        public Criteria andSlotsLessThanOrEqualTo(Integer value) {
            addCriterion("slots <=", value, "slots");
            return (Criteria) this;
        }

        public Criteria andSlotsIn(List<Integer> values) {
            addCriterion("slots in", values, "slots");
            return (Criteria) this;
        }

        public Criteria andSlotsNotIn(List<Integer> values) {
            addCriterion("slots not in", values, "slots");
            return (Criteria) this;
        }

        public Criteria andSlotsBetween(Integer value1, Integer value2) {
            addCriterion("slots between", value1, value2, "slots");
            return (Criteria) this;
        }

        public Criteria andSlotsNotBetween(Integer value1, Integer value2) {
            addCriterion("slots not between", value1, value2, "slots");
            return (Criteria) this;
        }

        public Criteria andOrderlistIsNull() {
            addCriterion("orderlist is null");
            return (Criteria) this;
        }

        public Criteria andOrderlistIsNotNull() {
            addCriterion("orderlist is not null");
            return (Criteria) this;
        }

        public Criteria andOrderlistEqualTo(String value) {
            addCriterion("orderlist =", value, "orderlist");
            return (Criteria) this;
        }

        public Criteria andOrderlistNotEqualTo(String value) {
            addCriterion("orderlist <>", value, "orderlist");
            return (Criteria) this;
        }

        public Criteria andOrderlistGreaterThan(String value) {
            addCriterion("orderlist >", value, "orderlist");
            return (Criteria) this;
        }

        public Criteria andOrderlistGreaterThanOrEqualTo(String value) {
            addCriterion("orderlist >=", value, "orderlist");
            return (Criteria) this;
        }

        public Criteria andOrderlistLessThan(String value) {
            addCriterion("orderlist <", value, "orderlist");
            return (Criteria) this;
        }

        public Criteria andOrderlistLessThanOrEqualTo(String value) {
            addCriterion("orderlist <=", value, "orderlist");
            return (Criteria) this;
        }

        public Criteria andOrderlistLike(String value) {
            addCriterion("orderlist like", value, "orderlist");
            return (Criteria) this;
        }

        public Criteria andOrderlistNotLike(String value) {
            addCriterion("orderlist not like", value, "orderlist");
            return (Criteria) this;
        }

        public Criteria andOrderlistIn(List<String> values) {
            addCriterion("orderlist in", values, "orderlist");
            return (Criteria) this;
        }

        public Criteria andOrderlistNotIn(List<String> values) {
            addCriterion("orderlist not in", values, "orderlist");
            return (Criteria) this;
        }

        public Criteria andOrderlistBetween(String value1, String value2) {
            addCriterion("orderlist between", value1, value2, "orderlist");
            return (Criteria) this;
        }

        public Criteria andOrderlistNotBetween(String value1, String value2) {
            addCriterion("orderlist not between", value1, value2, "orderlist");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table upstreams
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 24 14:53:05 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table upstreams
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}