package com.app.entity;

import java.util.Date;

public class Upstreams {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upstreams.id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upstreams.name
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upstreams.slots
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Integer slots;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upstreams.orderlist
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private String orderlist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upstreams.created_at
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upstreams.id
     *
     * @return the value of upstreams.id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upstreams.id
     *
     * @param id the value for upstreams.id
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upstreams.name
     *
     * @return the value of upstreams.name
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upstreams.name
     *
     * @param name the value for upstreams.name
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upstreams.slots
     *
     * @return the value of upstreams.slots
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Integer getSlots() {
        return slots;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upstreams.slots
     *
     * @param slots the value for upstreams.slots
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setSlots(Integer slots) {
        this.slots = slots;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upstreams.orderlist
     *
     * @return the value of upstreams.orderlist
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public String getOrderlist() {
        return orderlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upstreams.orderlist
     *
     * @param orderlist the value for upstreams.orderlist
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setOrderlist(String orderlist) {
        this.orderlist = orderlist == null ? null : orderlist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upstreams.created_at
     *
     * @return the value of upstreams.created_at
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upstreams.created_at
     *
     * @param createdAt the value for upstreams.created_at
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}