package com.app.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role_type
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    private String roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created_at
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_use
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    private String isUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_login
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    private Date lastLogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role_type
     *
     * @return the value of user.role_type
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role_type
     *
     * @param roleType the value for user.role_type
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created_at
     *
     * @return the value of user.created_at
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created_at
     *
     * @param createdAt the value for user.created_at
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_use
     *
     * @return the value of user.is_use
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    public String getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_use
     *
     * @param isUse the value for user.is_use
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    public void setIsUse(String isUse) {
        this.isUse = isUse == null ? null : isUse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_login
     *
     * @return the value of user.last_login
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_login
     *
     * @param lastLogin the value for user.last_login
     *
     * @mbggenerated Mon Jul 24 16:16:28 CST 2017
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
}