spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:postgresql://10.0.254.21:5432/kong
    username: kong
    password: kong
    driver-class-name: org.postgresql.Driver
    minIdle: 1
    maxActive: 2
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxWait: 60000
    poolPreparedStatements: true
    filters: stat


mybatis:
  mapperLocations: classpath*:com/app/mapper/*.xml
  typeAliasesPackage: com.app.entity

kong:
  baseurl: http://10.0.254.21:8001
  requrl: http://10.0.254.21:8000
