package com.app.mapper;

import com.app.entity.Apis;
import com.app.entity.ApisExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ApisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int countByExample(ApisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int deleteByExample(ApisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int insert(Apis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int insertSelective(Apis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    List<Apis> selectByExample(ApisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    Apis selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") Apis record, @Param("example") ApisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int updateByExample(@Param("record") Apis record, @Param("example") ApisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int updateByPrimaryKeySelective(Apis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apis
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int updateByPrimaryKey(Apis record);
}