package com.app.mapper;

import com.app.entity.Consumers;
import com.app.entity.ConsumersExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ConsumersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumers
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int countByExample(ConsumersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumers
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int deleteByExample(ConsumersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumers
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumers
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int insert(Consumers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumers
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int insertSelective(Consumers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumers
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    List<Consumers> selectByExample(ConsumersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumers
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    Consumers selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumers
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") Consumers record, @Param("example") ConsumersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumers
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int updateByExample(@Param("record") Consumers record, @Param("example") ConsumersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumers
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int updateByPrimaryKeySelective(Consumers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumers
     *
     * @mbggenerated Mon Jul 24 14:53:05 CST 2017
     */
    int updateByPrimaryKey(Consumers record);
}