package com.app.mapper;

import com.app.entity.KongUser;
import com.app.entity.KongUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface KongUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kong_user
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    int countByExample(KongUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kong_user
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    int deleteByExample(KongUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kong_user
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kong_user
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    int insert(KongUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kong_user
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    int insertSelective(KongUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kong_user
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    List<KongUser> selectByExample(KongUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kong_user
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    KongUser selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kong_user
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    int updateByExampleSelective(@Param("record") KongUser record, @Param("example") KongUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kong_user
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    int updateByExample(@Param("record") KongUser record, @Param("example") KongUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kong_user
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    int updateByPrimaryKeySelective(KongUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kong_user
     *
     * @mbggenerated Thu Jul 27 09:56:02 CST 2017
     */
    int updateByPrimaryKey(KongUser record);

    List<KongUser> loginUser(Map<String, String> map);
}